#!/usr/bin/env bash

# Description: Runs composer commands in the backend container

set -e

source "${ROOT_DIR}/.docker/commands/utils/color.sh"

msg "${YELLOW}[INFO] Running composer $*${NOFORMAT}"

dip exec backend "cd /var/www && composer $*"
COMPOSER_EXIT_CODE=$?

if [ $COMPOSER_EXIT_CODE -ne 0 ]; then
    msg "${RED}[ERROR] Composer command failed with exit code: $COMPOSER_EXIT_CODE${NOFORMAT}"
    exit $COMPOSER_EXIT_CODE
fi

exit 0
